/* =============================================================
   TEMPERO BAIANO — conteúdo bilíngue (Espanhol / Português)
   ============================================================= */

const UI = {
  es: {
    nav_historia: "Nuestra historia",
    nav_menu: "Menú",
    nav_resenas: "Reseñas",
    nav_contacto: "Contacto",
    cta_pedir: "Pedir por WhatsApp",
    hero_badge: "Comida brasileña · La Plata",
    hero_title_1: "Un pedacito de ",
    hero_title_em: "Bahía",
    hero_title_2: " en cada plato",
    hero_sub: "Sabores auténticos del noreste de Brasil, cocinados con cariño y entregados en tu puerta en La Plata.",
    hero_cta_pedir: "Pedir ahora",
    hero_cta_menu: "Ver el menú",
    hero_meta_1_label: "Fundado en",
    hero_meta_1_val: "2022",
    hero_meta_2_label: "Reseñas",
    hero_meta_2_val: "5.0 ★",
    hero_meta_3_label: "Zona de entrega",
    hero_meta_3_val: "Casco urbano · La Plata",
    historia_eyebrow: "Nuestra historia",
    historia_titulo: "De Bahía a La Plata",
    historia_p1: "Tempero Baiano nació en 2022, del deseo simple y sincero de traer a la Argentina un pedacito de Brasil — no solo en la comida, sino en la forma de recibir.",
    historia_p2: "Todo comenzó con las ganas de compartir los sabores auténticos de Bahía con quien, lejos de casa, sentía nostalgia de ese condimento especial, y con quien, aun sin haber ido nunca a Brasil, quería descubrir algo nuevo y lleno de alma.",
    historia_p3: "Desde entonces, cada plato que sale de nuestra cocina lleva historia, tradición y el cariño de quien cocina pensando en hacer que el otro se sienta en casa.",
    historia_cita: "Hoy, Tempero Baiano es más que un restaurante: es un pedazo de Bahía que encontró su lugar en La Plata.",
    historia_firma: "Flavio · Itabuna, Bahía → La Plata",
    historia_selo_top: "Desde",
    historia_selo_bottom: "sabor de Bahía",
    menu_eyebrow: "El menú",
    menu_titulo: "Cada plato, un pedazo de Bahía",
    menu_sub: "Elaborado con ingredientes de calidad y las recetas de siempre. Elegí tu categoría favorita.",
    menu_tab_todos: "Todos",
    menu_tab_populares: "Los más pedidos",
    menu_tab_especiales: "Especiales de la casa",
    menu_tab_economico: "Económico",
    menu_tab_combos: "Combos + delivery",
    menu_tab_bebidas: "Bebidas",
    menu_tab_postres: "Postres",
    menu_nota: "Los precios pueden consultarse por WhatsApp o en nuestro catálogo. Las milanesas se sirven con guarnición a elección: papas fritas o ensalada de lechuga y tomate.",
    menu_nota_link: "Ver catálogo con precios",
    pedido_eyebrow: "Cómo pedir",
    pedido_titulo: "Tu pedido, en 3 pasos",
    pedido_1_titulo: "Elegí tu plato",
    pedido_1_texto: "Recorré el menú y elegí lo que se te antoje — o pedinos recomendaciones por WhatsApp.",
    pedido_2_titulo: "Escribinos por WhatsApp",
    pedido_2_texto: "Confirmamos tu pedido, la dirección y el método de pago directamente en el chat.",
    pedido_3_titulo: "Recibilo en tu puerta",
    pedido_3_texto: "Entregamos en el casco urbano de La Plata. Envío con costo fijo de $3.000.",
    horario_titulo: "Horarios de atención",
    zona_titulo: "Zona de entrega",
    zona_texto: "Av. 32 hasta Calle 71, de 31 hasta Av. 1 — La Plata, Provincia de Buenos Aires.",
    zona_costo: "Costo de envío en la zona: $3.000",
    dia_domingo: "Domingo",
    dia_lunes: "Lunes",
    dia_martes: "Martes",
    dia_miercoles: "Miércoles",
    dia_jueves: "Jueves",
    dia_viernes: "Viernes",
    dia_sabado: "Sábado",
    cerrado: "Cerrado",
    resenas_eyebrow: "Lo que dicen de nosotros",
    resenas_titulo: "Reseñas con sabor a verdad",
    contacto_eyebrow: "Contacto",
    contacto_titulo: "Hacé tu pedido hoy",
    contacto_sub: "Estamos a un mensaje de distancia. Elegí el canal que prefieras.",
    contacto_whatsapp_label: "WhatsApp",
    contacto_whatsapp_val: "+54 9 221 691-5445",
    contacto_email_label: "Email",
    contacto_insta_label: "Instagram",
    contacto_insta_val: "@temperobaianolp",
    contacto_ubicacion_label: "Ubicación",
    contacto_ubicacion_val: "La Plata, Buenos Aires, Argentina",
    footer_texto: "Hecho con cariño en La Plata.",
  },
  pt: {
    nav_historia: "Nossa história",
    nav_menu: "Cardápio",
    nav_resenas: "Avaliações",
    nav_contacto: "Contato",
    cta_pedir: "Pedir pelo WhatsApp",
    hero_badge: "Comida brasileira · La Plata",
    hero_title_1: "Um pedacinho da ",
    hero_title_em: "Bahia",
    hero_title_2: " em cada prato",
    hero_sub: "Sabores autênticos do nordeste do Brasil, feitos com carinho e entregues na sua porta em La Plata.",
    hero_cta_pedir: "Peça agora",
    hero_cta_menu: "Ver o cardápio",
    hero_meta_1_label: "Fundado em",
    hero_meta_1_val: "2022",
    hero_meta_2_label: "Avaliações",
    hero_meta_2_val: "5.0 ★",
    hero_meta_3_label: "Área de entrega",
    hero_meta_3_val: "Centro urbano · La Plata",
    historia_eyebrow: "Nossa história",
    historia_titulo: "Da Bahia para La Plata",
    historia_p1: "Tempero Baiano nasceu em 2022, do desejo simples e sincero de trazer para a Argentina um pedacinho do Brasil — não só na comida, mas no jeito de receber.",
    historia_p2: "Tudo começou com a vontade de compartilhar os sabores autênticos da Bahia com quem, longe de casa, sentia saudade daquele tempero especial, e com quem, mesmo sem nunca ter ido ao Brasil, queria descobrir algo novo e cheio de alma.",
    historia_p3: "Desde então, cada prato que sai da nossa cozinha carrega história, tradição e o carinho de quem cozinha pensando em fazer o outro se sentir em casa.",
    historia_cita: "Hoje, Tempero Baiano é mais do que um restaurante: é um pedaço da Bahia que encontrou seu lugar em La Plata.",
    historia_firma: "Flavio · Itabuna, Bahia → La Plata",
    historia_selo_top: "Desde",
    historia_selo_bottom: "sabor da Bahia",
    menu_eyebrow: "O cardápio",
    menu_titulo: "Cada prato, um pedaço da Bahia",
    menu_sub: "Preparado com ingredientes de qualidade e as receitas de sempre. Escolha sua categoria favorita.",
    menu_tab_todos: "Todos",
    menu_tab_populares: "Mais pedidos",
    menu_tab_especiales: "Especiais da casa",
    menu_tab_economico: "Econômico",
    menu_tab_combos: "Combos + delivery",
    menu_tab_bebidas: "Bebidas",
    menu_tab_postres: "Sobremesas",
    menu_nota: "Os preços podem ser consultados pelo WhatsApp ou no nosso catálogo. As milanesas são servidas com acompanhamento à escolha: batatas fritas ou salada de alface e tomate.",
    menu_nota_link: "Ver catálogo com preços",
    pedido_eyebrow: "Como pedir",
    pedido_titulo: "Seu pedido, em 3 passos",
    pedido_1_titulo: "Escolha seu prato",
    pedido_1_texto: "Navegue pelo cardápio e escolha o que tiver vontade — ou peça recomendações pelo WhatsApp.",
    pedido_2_titulo: "Chame no WhatsApp",
    pedido_2_texto: "Confirmamos seu pedido, o endereço e a forma de pagamento direto no chat.",
    pedido_3_titulo: "Receba na sua porta",
    pedido_3_texto: "Entregamos no centro urbano de La Plata. Frete com valor fixo de $3.000.",
    horario_titulo: "Horário de funcionamento",
    zona_titulo: "Área de entrega",
    zona_texto: "Av. 32 até Rua 71, de 31 até Av. 1 — La Plata, Provincia de Buenos Aires.",
    zona_costo: "Taxa de entrega na região: $3.000",
    dia_domingo: "Domingo",
    dia_lunes: "Segunda-feira",
    dia_martes: "Terça-feira",
    dia_miercoles: "Quarta-feira",
    dia_jueves: "Quinta-feira",
    dia_viernes: "Sexta-feira",
    dia_sabado: "Sábado",
    cerrado: "Fechado",
    resenas_eyebrow: "O que dizem sobre nós",
    resenas_titulo: "Avaliações com sabor de verdade",
    contacto_eyebrow: "Contato",
    contacto_titulo: "Faça seu pedido hoje",
    contacto_sub: "Estamos a uma mensagem de distância. Escolha o canal que preferir.",
    contacto_whatsapp_label: "WhatsApp",
    contacto_whatsapp_val: "+54 9 221 691-5445",
    contacto_email_label: "E-mail",
    contacto_insta_label: "Instagram",
    contacto_insta_val: "@temperobaianolp",
    contacto_ubicacion_label: "Localização",
    contacto_ubicacion_val: "La Plata, Buenos Aires, Argentina",
    footer_texto: "Feito com carinho em La Plata.",
  }
};

// Preço formatado (ARS)
function precoARS(valor){
  return "$" + valor.toLocaleString('es-AR');
}

const HORARIOS = [
  { dia_key: "dia_domingo", horas: [] },
  { dia_key: "dia_lunes", horas: ["09:00–16:00", "18:00–22:00"] },
  { dia_key: "dia_martes", horas: ["09:00–16:00", "18:00–22:00"] },
  { dia_key: "dia_miercoles", horas: ["09:00–16:00", "18:00–22:00"] },
  { dia_key: "dia_jueves", horas: ["09:00–16:00", "19:00–22:00"] },
  { dia_key: "dia_viernes", horas: ["09:00–16:00", "18:00–22:00"] },
  { dia_key: "dia_sabado", horas: ["09:00–16:30"] },
];

const MENU = [
  // --- MÁS PEDIDOS ---
  { id:"canelones-pollo", categoria:"populares", img:"canelones-pollo.jpg", precio:14000,
    nombre:{es:"Canelones de Pollo", pt:"Canelones de Frango"},
    desc:{es:"Canelones de pollo, arroz, papas fritas y ensalada rusa.", pt:"Canelones de frango, arroz, batatas fritas e salada russa."}},
  { id:"canelones-carne", categoria:"populares", img:"canelones-carne.jpg", precio:14000,
    nombre:{es:"Canelones de Carne", pt:"Canelones de Carne"},
    desc:{es:"Canelones de carne, arroz, papas fritas y ensalada rusa.", pt:"Canelones de carne, arroz, batatas fritas e salada russa."}},
  { id:"pollo-plancha", categoria:"populares", img:"pollo-plancha-cebolla.jpg", precio:14000,
    nombre:{es:"Pollo a la Plancha con Cebolla", pt:"Frango Grelhado com Cebola"},
    desc:{es:"Pollo a la plancha, poroto, arroz, puré de papas y ensalada rusa.", pt:"Frango grelhado, feijão, arroz, purê de batatas e salada russa."}},

  // --- ESPECIALES DE LA CASA ---
  { id:"feijoada", categoria:"especiales", img:"feijoada.jpg", precio:14000,
    nombre:{es:"Feijoada", pt:"Feijoada"},
    desc:{es:"Riquísimo plato brasileño con poroto negro, carne y panceta ahumada, pechito de cerdo y calabresa. Acompaña arroz, farofa, ensalada de tomate y naranja de postre.", pt:"Riquíssimo prato brasileiro com feijão preto, carne e bacon defumados, costelinha de porco e calabresa. Acompanha arroz, farofa, salada de tomate e laranja de sobremesa."}},
  { id:"picana-acebolada", categoria:"especiales", img:"picana-acebolada.jpg", precio:18000,
    nombre:{es:"Picaña Acebolada", pt:"Picanha na Cebola"},
    desc:{es:"Esquisita picaña acebolada acompañada de feijão tropeiro, arroz, papas fritas y ensalada de lechuga y tomate.", pt:"Deliciosa picanha na cebola acompanhada de feijão tropeiro, arroz, batatas fritas e salada de alface e tomate."}},
  { id:"carne-do-sol", categoria:"especiales", img:"carne-do-sol-mandioca.jpg", precio:15000,
    nombre:{es:"Carne do Sol con Mandioca", pt:"Carne do Sol com Mandioca"},
    desc:{es:"Carne do sol con mandioca frita, poroto, arroz con ajo y ensalada de lechuga y tomate.", pt:"Carne do sol com mandioca frita, feijão, arroz com alho e salada de alface e tomate."}},
  { id:"carne-guisada", categoria:"especiales", img:"carne-ternera-guisada.jpg", precio:15000,
    nombre:{es:"Carne de Ternera Guisada", pt:"Carne de Vitela Guisada"},
    desc:{es:"Carne cocida a fuego lento con papas, zanahoria y aceitunas en salsa casera. Acompaña arroz y puré de papas.", pt:"Carne cozida em fogo baixo com batatas, cenoura e azeitonas em molho caseiro. Acompanha arroz e purê de batatas."}},
  { id:"strogonoff-pollo", categoria:"especiales", img:"strogonoff-pollo.jpg", precio:14000,
    nombre:{es:"Strogonoff de Pollo", pt:"Strogonoff de Frango"},
    desc:{es:"Receta especial con crema de leche, champiñones, mostaza y cebolla. Acompaña arroz, papas paja y ensalada.", pt:"Receita especial com creme de leite, champignon, mostarda e cebola. Acompanha arroz, batata palha e salada."}},
  { id:"strogonoff-carne", categoria:"especiales", img:"strogonoff-carne.jpg", precio:14000,
    nombre:{es:"Strogonoff de Carne", pt:"Strogonoff de Carne"},
    desc:{es:"Con el sabor justo de mostaza, ketchup, crema de leche y champiñones. Acompaña arroz, papas paja y ensalada.", pt:"Com o sabor certo de mostarda, ketchup, creme de leite e champignon. Acompanha arroz, batata palha e salada."}},
  { id:"parmesana-pizza", categoria:"especiales", img:"parmesana-carne-pizza.jpg", precio:15000,
    nombre:{es:"Parmesana de Carne a la Pizza", pt:"Parmegiana de Carne à Pizza"},
    desc:{es:"Combo parmesana de carne a la pizza con arroz y ensalada rusa.", pt:"Combo parmegiana de carne à pizza com arroz e salada russa."}},
  { id:"berenjenas", categoria:"especiales", img:"berenjenas-parmesana.jpg", precio:15000,
    nombre:{es:"Berenjenas a la Parmesana", pt:"Berinjela à Parmegiana"},
    desc:{es:"Parmesana de berenjena con espaguetis al ajo y aceite, con papas fritas.", pt:"Parmegiana de berinjela com espaguete ao alho e óleo, com batatas fritas."}},

  // --- ECONÓMICO ---
  { id:"espaguetis-mozza", categoria:"economico", img:"espaguetis-mozzarella.jpg", precio:12000,
    nombre:{es:"Espaguetis con Queso Mozzarella", pt:"Espaguete com Queijo Mussarela"},
    desc:{es:"Espaguetis con queso, simple y sabroso.", pt:"Espaguete com queijo, simples e saboroso."}},
  { id:"arroz-primavera", categoria:"economico", img:"arroz-primavera-pollo.jpg", precio:14000,
    nombre:{es:"Arroz Primavera con Pollo", pt:"Arroz Primavera com Frango"},
    desc:{es:"Riquísimo arroz primavera con pollo y vegetales.", pt:"Riquíssimo arroz primavera com frango e legumes."}},
  { id:"pasta-bolognesa", categoria:"economico", img:"pasta-bolognesa.jpg", precio:12000,
    nombre:{es:"Pasta en Salsa Bolognesa", pt:"Massa ao Molho Bolonhesa"},
    desc:{es:"Pasta en salsa bolognesa natural, sin conservantes.", pt:"Massa ao molho bolonhesa natural, sem conservantes."}},
  { id:"milanesa-carne", categoria:"economico", img:"milanesa-carne.jpg", precio:14000,
    nombre:{es:"Milanesa de Carne", pt:"Milanesa de Carne"},
    desc:{es:"Milanesa de carne con guarnición a elección: papas fritas o ensalada.", pt:"Milanesa de carne com acompanhamento à escolha: batatas fritas ou salada."}},
  { id:"milanesa-pollo", categoria:"economico", img:"milanesa-pollo.jpg", precio:14000,
    nombre:{es:"Milanesa de Pollo", pt:"Milanesa de Frango"},
    desc:{es:"Milanesa de pollo con guarnición a elección: papas fritas o ensalada.", pt:"Milanesa de frango com acompanhamento à escolha: batatas fritas ou salada."}},
  { id:"milanesa-pollo-espaguetis", categoria:"economico", img:"milanesa-pollo-espaguetis.jpg", precio:15000,
    nombre:{es:"Milanesa de Pollo con Espaguetis Ajo y Aceite", pt:"Milanesa de Frango com Espaguete Alho e Óleo"},
    desc:{es:"Milanesa de pollo con espaguetis al ajo y aceite, con papas fritas.", pt:"Milanesa de frango com espaguete ao alho e óleo, com batatas fritas."}},

  // --- COMBOS ---
  { id:"combo-parmesana-carne", categoria:"combos", img:"combo-parmesana-carne.jpg", precio:16000,
    nombre:{es:"Parmesana de Carne + Gaseosa + Delivery", pt:"Parmegiana de Carne + Refrigerante + Delivery"},
    desc:{es:"Parmesana de carne con arroz y papas, muy sabrosa. Incluye gaseosa y delivery.", pt:"Parmegiana de carne com arroz e batatas, muito saborosa. Inclui refrigerante e delivery."}},
  { id:"combo-pollo-parmesana", categoria:"combos", img:"combo-pollo-parmesana.jpg", precio:16000,
    nombre:{es:"Pollo a la Parmesana + Gaseosa + Delivery", pt:"Frango à Parmegiana + Refrigerante + Delivery"},
    desc:{es:"Pollo a la parmesana con pasta ajo y aceite y papas fritas. Incluye gaseosa y delivery.", pt:"Frango à parmegiana com massa ao alho e óleo e batatas fritas. Inclui refrigerante e delivery."}},
  { id:"combo-bife", categoria:"combos", img:"combo-bife-acebolado.jpg", precio:16000,
    nombre:{es:"Bife Acebolado + Gaseosa + Delivery", pt:"Bife na Cebola + Refrigerante + Delivery"},
    desc:{es:"Bife acebolado con arroz y papas fritas. Incluye gaseosa y delivery.", pt:"Bife na cebola com arroz e batatas fritas. Inclui refrigerante e delivery."}},

  // --- BEBIDAS ---
  { id:"coca-cola", categoria:"bebidas", img:"coca-cola.jpg", precio:2900,
    nombre:{es:"Coca-Cola 500ml", pt:"Coca-Cola 500ml"},
    desc:{es:"Gaseosa Coca-Cola sabor original.", pt:"Refrigerante Coca-Cola sabor original."}},
  { id:"coca-cola-zero", categoria:"bebidas", img:"coca-cola-sin-azucar.jpg", precio:2900,
    nombre:{es:"Coca-Cola Sin Azúcar 500ml", pt:"Coca-Cola Sem Açúcar 500ml"},
    desc:{es:"Gaseosa Coca-Cola sin azúcar.", pt:"Refrigerante Coca-Cola sem açúcar."}},
  { id:"fanta", categoria:"bebidas", img:"fanta.jpg", precio:2900,
    nombre:{es:"Fanta Naranja 500ml", pt:"Fanta Laranja 500ml"},
    desc:{es:"Gaseosa Fanta sabor naranja.", pt:"Refrigerante Fanta sabor laranja."}},

  // --- POSTRES ---
  { id:"goiabada", categoria:"postres", img:"goiabada.jpg", precio:9000,
    nombre:{es:"Goiabada con Queso y Crema de Leche", pt:"Goiabada com Queijo e Creme de Leite"},
    desc:{es:"Dulce brasileño hecho directamente en Brasil, muy sabroso.", pt:"Doce brasileiro feito diretamente no Brasil, muito saboroso."}},
  { id:"dulce-banana", categoria:"postres", img:"dulce-banana.jpg", precio:7000,
    nombre:{es:"Dulce de Banana con Crema de Leche", pt:"Doce de Banana com Creme de Leite"},
    desc:{es:"Hecho con la fruta, azúcar, clavo y canela en rama.", pt:"Feito com a fruta, açúcar, cravo e canela em rama."}},
];

const RESENAS = [
  { texto:{ es:"Dios. Sin palabras. Hermoso todo. Me enamoré del bahiano.", pt:"Meu Deus. Sem palavras. Tudo lindo. Me apaixonei pelo baiano." }, plato:{es:"Carne guisada con verduras", pt:"Carne guisada com legumes"} },
  { texto:{ es:"La carne muy tierna, porción GRANDE, excelente.", pt:"A carne bem macia, porção GRANDE, excelente." }, plato:{es:"Carne guisada con verduras", pt:"Carne guisada com legumes"} },
  { texto:{ es:"Excelente. Segunda vez que pido. Muy abundante y rico. Gracias.", pt:"Excelente. Segunda vez que peço. Bem abundante e gostoso. Obrigado." }, plato:{es:"Canelones de Carne", pt:"Canelones de Carne"} },
  { texto:{ es:"Ingredientes de calidad, buen sabor y porción adecuada.", pt:"Ingredientes de qualidade, bom sabor e porção adequada." }, plato:{es:"Feijoada", pt:"Feijoada"} },
  { texto:{ es:"Muy buena relación precio-calidad. Volvería a pedir sin dudarlo.", pt:"Ótima relação custo-benefício. Pediria de novo sem pensar duas vezes." }, plato:{es:"Picaña con cebolla", pt:"Picanha na cebola"} },
];
